apiVersion: v2
name: ssl-storage
description: Helm chart for deploying the SSL Storage ACME/Let's Encrypt certificate manager service
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - ssl
  - certificates
  - acme
  - letsencrypt
sources:
  - https://github.com/arxignis/ssl-storage
maintainers:
  - name: Arxignis
    email: support@arxignis.com
