{{- if and .Values.domains.createConfig (eq .Values.sslStorage.domains.source "file") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssl-storage.fullname" . }}-domains
  labels:
    {{- include "ssl-storage.labels" . | nindent 4 }}
data:
  domains.json: |
    {{- toJson .Values.domains.items | nindent 4 }}
{{- end }}
